### ISSUE TITLE
Missing ,

### ISSUE THREAD

**Issue by SimonHauguel** [RemiVan-Boxem/Guide-LaTeX#1]
Please add it

**Comment by remivanboxem** [comment]
Bonjour 👋


Rémi VAN BOXEM

Étudiant en CIR2

-

***@***.******@***.***>

Mobile : 33 (0)6 52 49 98 26

www.isen-lille.fr<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.isen-lille.fr%2F&data=04%7C01%7Cremi.van-boxem%40student.yncrea.fr%7Caaf01c706db744aef77708d8861f9c1a%7C89734289a3cf40529021195a7bba4992%7C1%7C0%7C637406817829090093%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f3%2F2a1hgpgXDvmC5XaRuI3eID7NGnBR8g18l4OfxioM%3D&reserved=0> - www.junia.com<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.junia.com%2F&data=04%7C01%7Cremi.van-boxem%40student.yncrea.fr%7Caaf01c706db744aef77708d8861f9c1a%7C89734289a3cf40529021195a7bba4992%7C1%7C0%7C637406817829095086%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Zrj%2FhDp4AfBYvsO7nwHDBDiRPNYQJ6dsVxrjv9RI9iA%3D&reserved=0>

________________________________
De : Simon Hauguel ***@***.***>
Envoyé : Tuesday, January 25, 2022 10:43:37 AM
À : RemiVan-Boxem/Guide-LaTeX ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [RemiVan-Boxem/Guide-LaTeX] Missing , (Issue #1)

Vous ne recevez pas souvent de courriers de la part de ***@***.*** Découvrez pourquoi cela est important<http://aka.ms/LearnAboutSenderIdentification>

Please add it
